### ISSUE TITLE
KitchenSink does not work after last changes

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#48]
### Steps to reproduce

KitchenSink navigation does not work after https://github.com/Starcounter/starcounter-include/pull/46:

1. Build KitchenSink (`73b8d7e62bf5cd5aba02e3fc13af1bf1c27fd023`)
2. `cd src/KitchenSink`
3. `bower install starcounter-include#a08f7ea24e3dffc38cd5072b03b3569227996732`
4. Run KitchenSink tests
   - or, to test manually: run KitchenSink, go to `localhost:8080/kitchensink` and try clicking on navigation in the left menu

**Comment by tomalec** [comment]
It seems that Kitchen sink uses non-namespaced view model (`MasterPage.html` and `CurrentPage`). Those are no longer supported with new version of `<starcounter-include>`

**Comment by warpech** [comment]
Good catch! 

If they are no longer supported, then why is it rendered on page load? If it is incorrect then it must fail early.

**Comment by tomalec** [comment]
Because we agreed to implement quick fix for https://github.com/Starcounter/starcounter-include/issues/34
didn't remove its support completely https://github.com/Starcounter/starcounter-include/issues/29

Also, we will not try to identify such cases. If some developer will mimic name-spaces with his/her view-model structure, I don't think it's reasonable to block it.

**Comment by tomalec** [comment]
@warpech, @Mihaiii can we close this one? Or is there something still not working?

**Comment by Mihaiii** [comment]
It was tested and merged. It's not my topic, but from my point of view it can be closed.

**Comment by warpech** [comment]
This was fixed in https://github.com/StarcounterApps/KitchenSink/pull/161, closing
