### ISSUE TITLE
Change Starcounter-Include to Synchronous

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/starcounter-include#54]
Change starcounter-include to work synchronously by default.

cc @Starcounter-Jack @alshakero @tomalec

**Comment by Joltrix** [comment]
Does this have anything to do with the [issue explained in Palindrom](https://github.com/Palindrom/Palindrom/issues/151)?

@Starcounter-Jack Won't it lag even more if starcounter-include is made to work synchronous rather than asynchronous?

**Comment by tomalec** [comment]
Could you elaborate on which part of sc-include you would like to make synchronous?

**Comment by tomalec** [comment]
And why? Looking and Heads performance problems, `<starcounter-include>` does not seem to be a part of the puzzle.

**Comment by Joltrix** [comment]
I am not sure, Perhaps @Starcounter-Jack or @stefanedqvist can answer that question and/or elaborate.

**Comment by stefanedqvist** [comment]
I can´t really. @tomalec I think you should call Joachim and talk to him directly

**Comment by tomalec** [comment]
We had a brief chat on it with Joachim. The idea is to try to minimize the number of micro-tasks needed to render nested partial (one that is nested itself and one that has nested sub partials).

One approach is the one we had before: inline entire HTML markup in JSON - that should be rendered extremely fast, the question is how about networking performance, but for sure we will lose all the features of HTML-Imports-driven partials (**per instance, per definition script execution**, the dependency tree, de-duping).

That's why I'm more keen into interim step between above and what we have now (cascade of partials being loaded asynchronously). I would imagine we could gather entire cascade into a single request and append everything more or less as one import and stamp already built content.

The issue was already stared at https://github.com/Starcounter/RebelsLounge/issues/127

In general, I would hold any serious work for the results of TPAC discussion on HTML Imports and HTML Modules.

**Comment by warpech** [comment]
As agreed today with @tomalec, we will return to this after TPAC. If HTML Imports/Modules do not get interest from W3C, then our way to go might be to inline views HTML in the boostraping HTML. That would allow us to abandon the HTML Import polyfill.

**Comment by warpech** [comment]
Closing as tracked in https://github.com/Starcounter/RebelsLounge/issues/127
